require('core.plugin_config.rose-pine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.gitsigns')
require('core.plugin_config.lsp-config')
require('core.plugin_config.cmp')
